### ISSUE TITLE
Product Feedback not working. Cannot add or update a child row: a foreign key constraint fails

### ISSUE THREAD

**Issue by gurnoors** [Kaushik-18/CMPE138-FeedbackManagmentDBProject#5]
This is what I tried to do:
![screen shot 2016-11-27 at 11 47 57 pm](https://cloud.githubusercontent.com/assets/12220080/20660009/f9220ee2-b4fb-11e6-9ff6-38f5f72467da.png)

Here is the traceback:

> Traceback (most recent call last):
  File "/Users/gurnoorsinghbhatia/PycharmProjects/CMPE138-FeedbackManagmentDBProject/ui/cli.py", line 258, in <module>
    next_operation = cli.show_main_menu()
  File "/Users/gurnoorsinghbhatia/PycharmProjects/CMPE138-FeedbackManagmentDBProject/ui/cli.py", line 194, in show_main_menu
    self.show_customer_feedback_entry()
  File "/Users/gurnoorsinghbhatia/PycharmProjects/CMPE138-FeedbackManagmentDBProject/ui/cli.py", line 71, in show_customer_feedback_entry
    self, customer_id=customer_id)
  File "/Users/gurnoorsinghbhatia/PycharmProjects/CMPE138-FeedbackManagmentDBProject/ui/actions.py", line 56, in insert_product_feedback
    fb.persist()
  File "/Users/gurnoorsinghbhatia/PycharmProjects/CMPE138-FeedbackManagmentDBProject/Core/app.py", line 91, in persist
    self.comments, self.franchise_id))
  File "/Users/gurnoorsinghbhatia/PycharmProjects/CMPE138-FeedbackManagmentDBProject/Core/DB.py", line 97, in insert_feedback_record
    values)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
_mysql_exceptions.IntegrityError: (1452, 'Cannot add or update a child row: a foreign key constraint fails (`cmpe138_project_team3_feedback`.`product_feedback`, CONSTRAINT `product_feedback_ibfk_1` FOREIGN KEY (`customer_id`) REFERENCES `customer` (`customer_id`) ON DELETE CASCADE)')

So, IMO this is because, given the following constraint (inside SQL script > create service feedback table)
`FOREIGN KEY (customer_id) REFERENCES customer (customer_id)
    ON DELETE CASCADE,`
we cannot insert customer_id in Service Feedback (in DB.py insert_feedback_record() ):

```python      
  if tablename == "product":
            cursor.execute(
                "INSERT INTO product_feedback(ratings,customer_id,"
                "product_id,comments,franchise_id)VALUES (%s,%s,%s,%s,%s)",
                values)
```

The above was what I inferred from the stack-trace. Now I am not sure about the following, but I think we first need to create a customer, only then can we refer it in any other (Service Feedback) table.

**Comment by gurnoors** [comment]
Ok this is not really a coding problem, but an unhandled case in application flow.
What about new customers? Where to give the option to add new customers.[ My suggestion](https://docs.google.com/document/d/1AWDKxYaZvibbuYqxVnycN3cPtaRfDxU4_uTfTekCMEw/edit?usp=sharing)

So (once I implement Customer ID existence check) we won't reach the case in the initial issue (insert new user in feedback table). A user needs to have an ID in order to give feedback.

@madhurkhandelwal234  or @khurana3773 , please review the addition to flow.
